version: "3"
services:

  back:
    image: eon01/quotes-back:v1
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: eon01/quotes-data:v1
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

networks:
  myapp:
