back:
  replicaCount: 3
  name: back
  container:
    image: eon01/quotes-back:v1
    name: api
    port:
      number: 3000
      name: http
  mysql:
    user: root
    password: root
    database: mydatabase
  service:
    name: back
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
data:
  name: data
  container:
    image: eon01/quotes-data:v1
    name: mysql
    env:
    - name: "MYSQL_USER"
      value: "root"
    - name: "MYSQL_PASSWORD"
      value: "root"
    - name: "MYSQL_DATABASE"
      value: "mydatabase"
    - name: "MYSQL_ROOT_PASSWORD"
      value: "root"
    port:
      containerPort: 3306
      name: mysql
    volumeMounts:
      name: mysql-persistent-storage
      mountPath: /var/lib/mysql
      subPath: mysql
    volume:
      name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv
  service:
    name: data
    port: 3306
    clusterIP: None
  pvc:
    name: mysql-pv
    resources:
      requests:
        storage: 10Gi

ingress:
  name: api-ingress
  global_static_ip_name: ip-address
  spec:
    rules:
    - host: quotes.local
      http:
        paths:
        - path: /*
          backend:
            serviceName: back
            servicePort: 80
